### ISSUE TITLE
restore windows / buffers after gtd processing

### ISSUE THREAD

**Issue by paschdan** [Trevoke/org-gtd.el#140]
hello, is there a way, that we can restore the window layout after processing is finished or aborted?

currently i loose all my buffer layout as soon as i start processing

**Comment by Trevoke** [comment]
Hi!

This feature is implemented in org-gtd V3, which literally just entered
beta testing.

If you are brave and comfortable with emacs, and willing to offer feedback
on things that break (because while I added tests, there's a lot of things
that are unpredictable in the real world), then the branch from which to
install the package is called "org-gtd-3".

If you are not comfortable, then I request a bit of patience while we iron
out the kinks :)

--

Aldric.

**Comment by Trevoke** [comment]
This should be fixed with the release of 3.0, please let me know / reopen if there is still a problem with this.

**Comment by Sabicool** [comment]
While it seems to restore the buffer I was working on, after processing my gtd inbox it does not restore the window configuration.
