### ISSUE TITLE
Review use of autoload cookies

### ISSUE THREAD

**Issue by doolio** [Trevoke/org-gtd.el#156]
Some but not all commands make use of `;;;###autoload` cookies. In addition, the public function `org-gtd-inbox-path` uses an autoload cookie when perhaps it should not? 

IIUC, these cookies should only be used with (user) points-of-entry. [This blog post ](https://swsnr.de/archive/2014/07/02/autoloads-in-emacs-lisp.html) is an excellent summary and suggests we could also remove the `org-gtd-autoloads.el` file from the repository.

We should review where we use these cookies, add any that are missing and remove any which are unnecessary.

**Comment by Trevoke** [comment]
Well, there's a few key entry points for users:

1. capturing (requires inbox path, capture function)
2. clarifying (from inbox, from random item, from agenda), which requires loading the whole organize bit as well
3. any of all of the review functions (oops, reviews, engage)
4. The minor mode

This means this package potentially has 15-20 autoload cookies, which maybe is completely fine, but now here's the really fun part.

To test that all the loading is correct, you need to basically restart emacs every time you want to test another autoload function so that nothing else is loaded and you can make sure that it properly loads everything it needs to.

Soooooooooo have fun?

This being said, if you submit a PR that removes the autoloads.el file and adds it to the gitignore instead, I'm happy to merge that in.

**Comment by doolio** [comment]
> This means this package potentially has 15-20 autoload cookies, which maybe is completely fine

I believe that should not be an issue.

> To test that all the loading is correct, you need to basically restart emacs every time you want to test another autoload function so that nothing else is loaded and you can make sure that it properly loads everything it needs to.

OK, thanks.

> This being said, if you submit a PR that removes the autoloads.el file and adds it to the gitignore instead, I'm happy to merge that in.

Yes, my thinking is to ensure all the autoloads we want exist and also remove the need for that file.

**Comment by Trevoke** [comment]
Okay, well, handling autoloads is very low on my list of priorities because of the amount of time I have to spend on it vs the amount of value that gets delivered, compared to other ways I can spend my time, so don't expect me to work on this for the next .... many months... , but if you want to work on that, and open a PR draft with a checklist of all commands, then we can see about commands that could or could not use the autoload cookies, and you (and others) can start working on this.

**Comment by Trevoke** [comment]
I think this is connected to https://github.com/Trevoke/org-gtd.el/issues/156

I've got some airplane time coming up soon, I'll likely be poking at that pull request then.

**Comment by Trevoke** [comment]
I meant to link this to https://github.com/Trevoke/org-gtd.el/pull/194 and not to itself.

I think we're in a decent autoloads spot now, so I'm going to close this issue, and we can add autoloads cookies maybe on an as-needed basis? Let me know, we can always reopen this issue, too :)
