### ISSUE TITLE
Question: How does incubate work?

### ISSUE THREAD

**Issue by jsandovalc** [Trevoke/org-gtd.el#17]
Hi again,

I'm trying to process a task by incubating it. I go to process (C-c d p), I press `i` to incubate it. It goes to the capture buffer. I press `C-c c`and it asks for tags. I introduce a couple and it prompts for a date in the calendar, then it shows me a refile with the headers of the inbox, I think. 

I see there is a `incubate.org` file. I tried adding some headers there but it stills shows the headers of `inbox.org`. Maybe, I'm doing something wrong. The README only indicates that incubations allow for later reviewing.

Thanks again.

**Comment by Trevoke** [comment]
The way incubate works right now is that it's just moving the headline to the `incubate.org` file -- because the item will naturally pop up in the agenda when it's time for you to review it.

I definitely *did* have an intent of further categorization, and of being able to refile to a slightly more refined incubator (as indicated by the comment at the top of that file) but right now that's not working; I need to add a test or two to figure out why it's not doing the right thing.

**Comment by samvidmistry** [comment]
I'm running into the same issue. I cannot incubate anything. It keeps asking for a refile subtree and the subtree root has to be something other than itself.

**Comment by Trevoke** [comment]
Okay, that's definitely broken, then. Two things:

First, could you paste two or three screenshots of the sequence?

Second, try adding to the incubate file something like this:

```
* Incubate
  * To read
```

and see if that makes a difference?

I will look at it this weekend and add a few tests to make sure this behavior doesn't regress again.

**Comment by jsandovalc** [comment]
Hi @Trevoke 

First, I apply `C-c d p` to process my inbox:

![screenshot](https://user-images.githubusercontent.com/5023589/90200262-c0f2dd80-dd9c-11ea-9c54-216e9f6c68c6.png)

Then I press `i` to incubate and it goes to the buffer. After that I press `C-c c` (in my case `C-c x`) to clarify. After that it asks for tags. After that it asks for a date to schedule:

![screenshot2](https://user-images.githubusercontent.com/5023589/90200358-1cbd6680-dd9d-11ea-9cf3-496119bd2f13.png)

And then it shows the refile menu:

![screenshot3](https://user-images.githubusercontent.com/5023589/90200410-555d4000-dd9d-11ea-881b-3e673d3dbada.png)

I tried adding headers to `incubate.org` but it always shows only the headers in `inbox.org`. There, it fails.

**Comment by Trevoke** [comment]
I've not forgotten about you!
There's something funky going on, because it looks a lot like the same logic as all other refiles but something's off, and I've been fighting my test suite all weekend.

The refile, in the code, happens at : https://github.com/Trevoke/org-gtd.el/blob/5e92b555e979f90a9aa02cf62e9c5e362409adf5/org-gtd.el#L361 
`(org-refile nil nil (org-gtd--refile-target org-gtd-incubate))`

And `(org-gtd--refile-target org-gtd-incubate)` should generate the refile options. It might be a regular expression issue (it _probably is_ a regular expression issue) ...

Anyway, I'm still working on that.

**Comment by Trevoke** [comment]
Okay, I have it fixed, and I've even added a few tests :D 

... Now I should work to make sure my build actually works... 

Please make sure your incubate file has some headers as suggested in the comment at the top of the file (or see the newly-created CHANGELOG for some information).

Above, I suggested doing this:

```
* Incubate
  * To read
```

You no longer need that `* Incubate`.
