### ISSUE TITLE
[Question] Add item to existing project and nested projects

### ISSUE THREAD

**Issue by samvidmistry** [Trevoke/org-gtd.el#18]
Is there a way to add an inbox item to an existing project as the next step after all added entries? Also can there be projects inside a project?

**Comment by Trevoke** [comment]
Hi!

1. Right now there isn't a way to add an inbox item to an existing project programmatically - you can mark it as a "reference" item, then do whatever you need with it manually.
2. There can't be projects inside projects (right now anyway). For myself, I have found it much easier overall to just create the projects inline - either multiple separate projects or one long one. I'm also unsure about the possible additional complexity of doing that, though maybe `org-edna` would make this not too painful. Can you say a bit more about what you have in mind, maybe with an example?

**Comment by samvidmistry** [comment]
Let's say I have a top level project for a course at my college. That becomes one project. Then I have assignments, which is a subproject in that. I have a list of readings, which is also a subproject. Let's say that in assignments I have multiple assignments and each assignment has multiple steps for completion, so each assignment might also be a subproject under the assignments subproject. So if I can add subprojects then it would be a great way to organise all my projects. The whole course as a subproject is not suitable because that'll show me only one next item, while I need separate next items for multiple things that I am required to do in a course.

Does that make sense? Is there a better alternative to this sort of arrangement? I'm pretty new to this GTD thing and org mode so I'm open to suggestions.

**Comment by Trevoke** [comment]
I see!

Okay, so obvious first thing, I recommend buying the GTD book :D 

Projects should be defined as unambiguously doable and finishable things. 

A college course probably isn't a project, because, you can't *do* it.. You can attend the classes, you can do the homework, but .. The course is just a thing. A college course might be better defined as a custom property (for instance `C-c C-x p COURSE RET <course name> RET`).

"Assignments" doesn't make much sense as a project. Technically you're done with the assignment project when you're done with all the assignments, but it's not very meaningful; it might be more valuable as a tag (`C-c C-q`), defining the type of work this is, or maybe a GTD context (defining "when I am in this context, I can do this kind of work").

 Based on all this, maybe a project could look something like this: 

```
* Write paper on Final Fantasy VII                               :assignment:
:PROPERTIES:
:COURSE:   Storytelling in Video Games
:END:
** Get "Essential Elements of Storytelling" from library           :@campus:
** Read chapter 7 of Ess Elt of Story                               :@nonet:
** Write outline                                                    :@emacs:
** Get quick first draft out                                        :@emacs:
** Return Ess Elt of Story                                         :@campus:
```

**Comment by samvidmistry** [comment]
That's great. I'll try this method. Meanwhile, I'm closing this issue. I'll reopen if I have other queries. Thanks.

**Comment by Trevoke** [comment]
I've just merged in code that allows one to move a task to an existing project! If you're still using this package, try it when MELPA updates and let me know how it goes :D
