### ISSUE TITLE
Archive location issue and Delegated/Blocked visibility

### ISSUE THREAD

**Issue by Xalielt** [Trevoke/org-gtd.el#180]
Thanks for the package, am having fun testing it against my workflows.

Just getting to grips with It and finding a few items. 

1. With calling org-gtd-engage after initial load get the following - "let*: Symbol’s value as variable is void: org-gtd-archive-location".
Am able to get this to work by calling org-gtd-organize in the scratch buffer which then seems to resolve the above. Set-up is fairly formulaic although is a custom org-gtd-directory.

2. With org-gtd-engage the Delegated/ Blocked items is running blank. Believe this is that org-todo-ignore-with date is set to 't' in the function.

3. Specific to my set-up. Found that as I use dynamic grabbing of org-agenda-files from an Org-Roam directory (modified from - -https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html). Found that the org-gtd-core--agenda-files is adding the gtd directory which in my case is also the roam directory. Results in massive amount of files being brought in to the agenda for me. 
Have modded the function for own purposes to test out. Would be a good enhancement to optionally remove the (ensure-list org-gtd-directory) from the function.
This allows me to have actions / projects/ etc. in any Roam file. 

Cheers

**Comment by Trevoke** [comment]
Hello! Thanks for trying out the package!

1. Please try to do a full load of the package with `(require 'org-gtd)` and let me know if this makes the problem go away
2. Do you have any delegated/blocked items that have been set to show up on this particular day? 
3. It sounds like you are surprised that we are bringing in the `org-gtd-directory` to generate the agenda; what exactly did you think was supposed to happen, and why did you think that was supposed to happen? 

On a related topic - why do you think `ensure-list` could be the problem (it isn't, it's there because of one of the possible ways that `org-agenda-files` is allowed to work, which is that it can be a single file which contains a list of the actual files)?

It sounds like what you want is to have a full directory of files which _could_ have org-agenda data, and that emacs and org-mode would be able to not load everything in order to know which files are relevant?

The pure GTD way of handling this would be to tell you that you shouldn't put your task management inside your knowledge management; GTD *specifically* places knowledge management as a *destination* for non-tasks, so what you're trying to do with org-roam sounds like it's the complete opposite of how GTD wants to think.

This being said, this is emacs, and you're supposed to be able to do whatever you want, so .... What *do* you want exactly?

**Comment by Trevoke** [comment]
1 should no longer be a problem

2 should be "fixed" (that section was indeed broken, but delegated items due today show up in the first block)

3 this is a tricky design decision. Part of the intent of org-gtd is to minimize the amount of setup required. If you have custom needs (e.g. you have decided that you want your task management to be the same thing as your todo list) you can currently override/advise the function `org-gtd-core--agenda-files` to return the list of files you want to include. I have to consider what it can be like to make this customizable... At some point I'm just recreating org-mode on top of org-mode.
