### ISSUE TITLE
When i try to move items to "project" nothing happens

### ISSUE THREAD

**Issue by vignesh-TG** [Trevoke/org-gtd.el#35]
While processing the items in the inbox.org file, if select "p" for shelving it under project, nothing happens. The item still exists in the inbox.org.  The items have not moved to "Projects" heading in actionable.org file.
How to properly create projects and add items to it ?

**Comment by Trevoke** [comment]
@vignesh-TG 

I need to record a small video for this. 

Given this inbox:

```
# inbox
* My first item
```

When you process the items, you will see:

```
[ Clarify item; hit C-c c to finish ]
* My first item
```

When you hit `p` you end up with 

```
[ Clarify item; hit C-c c to finish ]
* My first item
```

again.

At this point, you create the project you want. A project has a title and at least one step (though probably two otherwise it would be a single action), so something like this:

```
[ Clarify item; hit C-c c to finish ]
* My first item
** My first action
** My second action
```

Then when you hit `C-c c` it'll finish processing the item and you'll be returned to an empty inbox. Now you can go check the `actionable.org` file, save it, reload your agenda, and you should see the first item.

**Comment by vignesh-TG** [comment]
Hi Trevoke,

Thanks for helping out.  After I come to the last step. I get the error "NEXT is not a valid TODO state" displayed.
I am using the configurations as given in "Configuring"  section in the README.org file.


-Vignesh

**Comment by Trevoke** [comment]
If you used exactly what I wrote above that's normal. Delete your inbox
file and try adding an item through the org capture functionality - one
feature of this path is that it will initialize the inbox for you, among
other things with the required TODO states.



--

Aldric.

**Comment by vignesh-TG** [comment]
It works, after i delete the inbox file. 
Thank you very much for the clarification

**Comment by vignesh-TG** [comment]
It works, after i delete the inbox file.
Thank you very much for the clarification
