### ISSUE TITLE
org-gtd--project: Wrong number of arguments: (first-entry . rest-entries), 0

### ISSUE THREAD

**Issue by codygman** [Trevoke/org-gtd.el#36]
It could be because I use emacs 28.

**Comment by bepolymathe** [comment]
Could you explain a bit more what you did? I had the same kind of mistake at the beginning...

**Comment by Trevoke** [comment]
hi @codygman , did the link above help solve your issue?

**Comment by Trevoke** [comment]
@codygman I will close this issue; I have made significant changes to the README, which I hope will help you avoid this problem in the future. If this does not help, please let me know and we'll work together to make this more clear.

What you ran into is something which I thought would be very helpful but turned out to be incredibly non-obvious to almost everyone, so I am doing a lot of work to make this better.

**Comment by codygman** [comment]
@Trevoke Hey, I might have to give it a try again in the future. Thanks for your hard work! :slightly_smiling_face:
