### ISSUE TITLE
[Question] Possible to use Projects per file?

### ISSUE THREAD

**Issue by poulpoulsen** [Trevoke/org-gtd.el#4]
Hello,
as far as i understand the documentation, i find nothing about using multiple files for different projects.
E.g.: Usually and currently with org i use one file per Projects or private things.
One file for my things, one for my wife, one per project.

Is this possible?

Regards
Poul

**Comment by Trevoke** [comment]
Hi @poulpoulsen -- this is currently not built-in, because I have been trying to keep the interface very simple, and org-mode's code has some pretty tight coupling.

Since we're asking the user to add a whole directory for the org agenda, it's easy enough to have any number of files, however refiling is a little bit trickier.

Possibly the simplest thing we could do to support multiple files is provide an escape hatch in the processing loop, for "user action" (none of these default actions work for me, let me do my own). This would let you do your own refiling - you would have to manage your own refiling configuration, though.

Currently, the imagined behavior is that this kind of categorization can be done through [tags](https://orgmode.org/manual/Setting-Tags.html#Setting-Tags) or [properties](https://orgmode.org/manual/Property-Syntax.html#Property-Syntax).

Would you be able to tell me why tags or properties wouldn't be sufficient for what you're trying to do?

**Comment by poulpoulsen** [comment]
Thanks for the answer!
the only reason i have to work with different files is:
my different files are connected with projects and private diy things.
they tend to grow...
so i decided to cut off in pieces, because org-mode tend to have lag, if they are growing.

Regards
Poul
