### ISSUE TITLE
org-gtd-show-stuck-projects surfaces completed projects

### ISSUE THREAD

**Issue by mobatmedia** [Trevoke/org-gtd.el#61]
The function org-gtd-show-stuck-projects is supposed to surface projects without NEXT items. However, it also surfaces projects that have no TODO items. This means that completed projects will always show up in that list. The only workarounds I see involve manual processes, which seems contrary to the point of org-gtd.

**Comment by Trevoke** [comment]
Ah! Good call.

I will add logic to make sure these completed projects do not show up.

In the meanwhile, please note that `(org-gtd-archive-complete-projects)` exists so that completed projects are removed from the list of active projects, moved to the archive file. This should help. A future enhancement might automatically move the project to the archive file when the last item is DONE.

**Comment by mobatmedia** [comment]
Thank you. 

Should you decide to implement an automatic move, would you please make that customizable?
