### ISSUE TITLE
Refile tasks that have already been processed

### ISSUE THREAD

**Issue by jhp0tter** [Trevoke/org-gtd.el#97]
Hi,

First of all I want to say that I really appreciate this package.

One issue I've noticed while using it is that sometimes when processing my inbox I make mistakes. For example, I initially refiled a task as a Single Action but later decided that it should instead be in the Calendar. But when this happens there doesn't seem to be any way to go back and re-file this task besides editing manually.

**Comment by cdlm** [comment]
Similar impression here, just started adopting org-gtd, and I expected `org-gtd-choose` to work on already filed tasks.

My concrete use-case was that I had `org-gtd-refile-to-any-target` true and a couple tasks were refiled to the wrong file; but one legitimate use-case is when you decide to de-incubate a task; you might want to:
- schedule it,
- convert it into a project because it was incubated as an abstract non-actionable description and it ends up to be multi-step
- move it to an *area of responsibility* file (I have several of those, each with their own action/project/calendar… headings)

**Comment by Trevoke** [comment]
This is implemented as part of 3.0, this issue will be closed when the PR is merged and 3.0 is ready for beta testing.
